---
name: Cut release for tag
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.2'
          cache: true

      - name: Install tools
        run: |
          echo "Installing enumer"
          go install github.com/dmarkham/enumer@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          ls -la $HOME/go/bin
          echo "Current PATH: $PATH"

      - name: Generate code
        run: |
          echo "Running go generate"
          go generate -v ./...
          echo "Go Generate completed"

      - name: Get current tag
        run: |
          echo "VERSION=$(git describe --tags)" >> "${GITHUB_ENV}"

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
