---
name: Cut release for tag
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  call-prepare-env:
    uses: ./.github/workflows/prepare-env.yaml
    with:
      goVersion: '1.22.2'

  release:
    needs: call-prepare-env
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-files
          path: temp_download

      - name: Move and check files
        run: |
          cp -rf temp_download/* .
          rm -rf temp_download
          ls -la

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.2'
          cache: true

      - name: Get current tag
        run: |
          echo "VERSION=$(git describe --tags)" >> "${GITHUB_ENV}"

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
